#!/usr/bin/env Rscript

args <- commandArgs(trailingOnly = TRUE)

infile <- args[1]

dat <- read.table(infile, col.names = c("Length"))

png(filename = "./plot_Length_of_Exons")
hist(log(dat$Length), xlab = "log(Length of Exons)", main = NULL, col = "lightseagreen")
dev.off()
