#!/usr/bin/env Rscript

args <- commandArgs(trailingOnly = TRUE)

infile <- args[1]

dat <- read.table(infile, col.names = c("Length"))

png(filename = "./plot_Sequence_Length_Distribution")
hist(log2(dat$Length), xlab = "log2(Length of Sequence)", main = NULL, col = "orange1")
dev.off()










